language: java

sudo: required

notifications:
email: james.hn.sears@gmail.com

addons:
  sonarcloud:
    organization: "jameshnsears-github"
    token:
      secure: "mRVFpQpK+8YhRgHUzVmnm/EttxBwOwn05LU9CCvG2P6jOVy7ESwigYok4yS5fsK252fXDu9F+BNXe0E05TgsgMhB4RzwKrsOevpAWSmQLivm5dS67TACygQmecmuFziT/TQMUCA+1G+Wobe7IQJEe/AfWBU4Y9ZtYjQDikuoVU8nuJenWluXaITGVGF9tL6puUdTsYWBtBkRzjibDPasYN40fX9ScDNVGDUGJNheqNLQwAJYOOcUY+pnxuON3qzPVdU4jvwKTFv56ISCrxvfwulo9Eml5c/3rfPjgaWaZ8+99f7n3oogT7mFs293aky/U9MOSGpsw/LEQZ+3/+rZeIOWMMfoQrrfZNo/TPxLTDCo5rcJSwRn5ydkpD3sVEh8fpIbipA9xfooWjYXMVNWKZCyP8B62r5xHUZoa7HxR41CUqRU5oq6PEUxLrzI4UFzyzd5dekXDpWwQHfFyDWe/VYI8BSOCbYEKutuu30xTqZO+9KBgwtG953NyRFOSMlMYGlXkXUMy6oHMuyN0nw5EvwSJew4qKdBWoh+34fMM50Xhg4j9Sen2u8NHERdBiGutN8U9TzyBPFaouw9DhArlILGdNQoDDgIES76lTJlf1AjOhYdRQcjIopQ09AIwo/P2wxhT5o+2FbUFRRIsXnNGM3e9cHfzbLB9OyAY0+jVzA="

services:
  - docker

jdk:
  - openjdk10

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

before_script:
  - docker-compose up -d xqa-message-broker

script:
  - mvn clean test
  - mvn checkstyle:check spotbugs:check pmd:pmd

after_success:
  - mvn jacoco:report coveralls:report
  - sonar-scanner
