sudo: required

notifications:
email: james.hn.sears@gmail.com

services:
  - docker

language: python

python:
  - "3.5"
  - "3.6"

before_script:
  - docker network create xqa

  - docker volume create xqa-message-broker
  - docker pull jameshnsears/xqa-message-broker
  - docker run -d --net="xqa" --name="xqa-message-broker" -p 5672:5672 jameshnsears/xqa-message-broker

  - sudo apt-get remove cmake
  - sudo apt-get install -y gcc cmake-curses-gui uuid-dev libssl-dev libsasl2-2 libsasl2-dev swig python-dev python3-dev ruby-dev libperl-dev

  - pip install -r requirements.txt

script:
  - export PYTHONPATH=/home/travis/build/jameshnsears/xqa-ingest/src:$PYTHONPATH
  - coverage run --omit */site-packages/*,*/virtualenv/* src/xqa/ingester.py -p test/resources/test-data/good
  - mkdir coverage
  - mv .coverage coverage/.coverage.0

  - pytest --flake8 --cov-report term-missing --cov=. test
  - mv .coverage coverage/.coverage.1

after_success:
  - cd coverage
  - coverage combine
  - codecov --token=98e1e4b3-b943-4009-9e90-371b0ac5237d
  - COVERALLS_REPO_TOKEN=umsIY7d4uf3Ay5aeMisTKDmrCpAM3Svu8 coveralls
