version: '3'

services:
  xqa-message-broker:
    image: jameshnsears/xqa-message-broker:latest
    ports:
      - "5672:5672"
      - "8161:8161"
    volumes:
      - "xqa-message-broker:/opt/apache-activemq-5.15.3/data"
    networks:
      - xqa

  xqa-ingest:
    build: .
    image: "xqa-ingest"
    command: ["-message_broker_host", "xqa-message-broker", "-p", "$HOME/GIT_REPOS/xqa-test-data"]
    networks:
      - xqa
    depends_on:
      - xqa-message-broker

volumes:
  xqa-message-broker:

networks:
  xqa:
