version: '3'

services:
  xqa-ingest:
    build: .
    image: xqa-ingest
    container_name: xqa-ingest
    command: ["-message_broker_host", "xqa-message-broker"]
    depends_on:
      - xqa-message-broker
    networks:
      - xqa

  xqa-message-broker:
    image: jameshnsears/xqa-message-broker:latest
    container_name: xqa-message-broker
    ports:
      - "5672:5672"
      - "8161:8161"
    volumes:
      - "xqa-message-broker:/opt/apache-activemq-5.15.7/data"
    networks:
      - xqa

volumes:
  xqa-message-broker:

networks:
  xqa:
